### PR TITLE
Adaptation for librosa 0.10

### PR DESCRIPTION
**Pull request by Sieroy**
在librosa更新到0.10版本后，使用`librosa.filters.mel`函数必须使用关键字参数，使用位置参数会报错：
```
mel() takes 0 positional arguments but 5 were given
```
这里根据此进行了小修正，并且在Colab上经测试可以通过。

### CODE REVIEW

**Comment by justinjohn0306** [comment]
@Sieroy can you share the link to ljs_windows pretrained model?

**Comment by Sieroy** [comment]
> @Sieroy can you share the link to ljs_windows pretrained model?

@justinjohn0306 

Did you mean the model mentioned in the README?
Link：https://pan.baidu.com/s/1pN-wL_5wB9gYMAr2Mh7Jvg
Password：vits

If you are not in China or don't have VIP privillege of BaiduNetDisk, you can try [this](
https://drive.google.com/folderview?id=1_8IReYt2ZFnv4TExqz3QAJ0KvJdbTL47).

By the way, this model is pretrained to speak mandarin Chinese, and maybe not suitable for other language without tons of fine tuning.

当然如果你要搞中文TTS的话那就莫得问题。

Good luck.

**Comment by justinjohn0306** [comment]
Yeah I'm looking to train a English vits model

**Comment by Sieroy** [comment]
我大意了在更新fork出来的repo时忘了brunch，于是好多其他东西被这条pr收进来了。
于是开了另一个pr呜呜呜。这条PR就关了吧。
#6

**Pull request closed without merging**
